id: P003204
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:47:17.901821
source_metadata:
  id: bdr:W1KG25195
  title: ཚད་མ་རིག་གཏེར་དར་ཊཱིཀ་དང་བདེན་གཉིས་ཀྱི་དར་ཊཱིཀ།
  author: ''
  volumes:
    cf6ec0bd23c144919700f8dc28dbf79b:
      image_group_id: I1KG25197
      title: ''
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
